//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Chapter {
            get {
                object obj = ResourceManager.GetObject("Chapter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Clean {
            get {
                object obj = ResourceManager.GetObject("Clean", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon computer {
            get {
                object obj = ResourceManager.GetObject("computer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup Condition=&quot;&apos;$(Configuration)|$(Platform)&apos;==&apos;Debug|Win32&apos;&quot;&gt;&lt;LocalDebuggerCommand&gt;{0}hl2.exe&lt;/LocalDebuggerCommand&gt;&lt;/PropertyGroup&gt;
        ///  &lt;PropertyGroup Condition=&quot;&apos;$(Configuration)|$(Platform)&apos;==&apos;Debug|Win32&apos;&quot;&gt;&lt;LocalDebuggerCommandArguments&gt;-dev -windowed -novid -game &quot;{1}&quot;&lt;/LocalDebuggerCommandArguments&gt;&lt;/PropertyGroup&gt;
        ///  &lt;PropertyGroup Condition=&quot;&apos;$(Configuration) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPP_UserTemplate {
            get {
                return ResourceManager.GetString("CPP_UserTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder_Closed {
            get {
                object obj = ResourceManager.GetObject("Folder_Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Folder_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FormRunHS {
            get {
                object obj = ResourceManager.GetObject("FormRunHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Hard_Drive {
            get {
                object obj = ResourceManager.GetObject("Hard_Drive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Keys {
            get {
                object obj = ResourceManager.GetObject("Keys", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Light {
            get {
                object obj = ResourceManager.GetObject("Light", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Localization {
            get {
                object obj = ResourceManager.GetObject("Localization", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon modern_install_full {
            get {
                object obj = ResourceManager.GetObject("modern_install_full", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ModMaker {
            get {
                object obj = ResourceManager.GetObject("ModMaker", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModMaker128 {
            get {
                object obj = ResourceManager.GetObject("ModMaker128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;======DO NOT EDIT BEYOND THIS POINT======
        ///
        ///!ifdef ZIPDLL
        ///	!include &quot;zipdll.nsh&quot;
        ///!endif
        ///
        ///var STEAMEXE
        ///
        ///!include &quot;MUI.nsh&quot;
        ///!define MUI_ABORTWARNING
        ///!insertmacro MUI_PAGE_COMPONENTS
        ///!insertmacro MUI_PAGE_INSTFILES
        ///!insertmacro MUI_LANGUAGE &quot;English&quot;
        ///
        ///Name &quot;${PRODUCT_NAME} ${PRODUCT_VERSION}&quot;
        ///OutFile &quot;${PRODUCT_NAME}.exe&quot;
        ///ShowInstDetails show
        ///
        ///!ifndef NO_DESKTOP_ICON
        ///Section &quot;Desktop Shortcut&quot; SHORTCUT
        ///	ReadRegStr $R0 HKCU &quot;Software\Valve\Steam&quot; SteamPath
        ///	SetOutPath &quot;$R0\steamapps\common\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NSI_Footer {
            get {
                return ResourceManager.GetString("NSI_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon orange_install {
            get {
                object obj = ResourceManager.GetObject("orange_install", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //QC Script generated by Mod Maker
        ///// Output .MDL
        ///$modelname {1}.mdl
        ///
        ///// Directory of .VMTs
        ///$cdmaterials models/
        ///$staticprop
        ///
        /////$scale 1.0
        ///
        ///// whole body
        ///$body studio &quot;{0}&quot;
        ///
        ///$surfaceprop {2}
        ///
        ///// sequences: all sequences are in $cd
        ///$sequence idle &quot;{0}&quot; loop fps 1
        ///
        ///$collisionmodel &quot;{0}&quot;.
        /// </summary>
        internal static string QCTemplate {
            get {
                return ResourceManager.GetString("QCTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/ValveSoftware/source-sdk-2013/archive/master.zip.
        /// </summary>
        internal static string SDK_2013_URL {
            get {
                return ResourceManager.GetString("SDK_2013_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Sound {
            get {
                object obj = ResourceManager.GetObject("Sound", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Weapon {
            get {
                object obj = ResourceManager.GetObject("Weapon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
